### ISSUE TITLE
version 1.5.5 and 1.5.6 doesn't run properly on High Sierra.

### ISSUE THREAD

**Issue by gearboxscott** [asciidocfx/AsciidocFX#329] opened 2017-10-19 18:30 UTC
Hi,

I have upgrade the mac to High Sierra.  AsciidocFX starts, prompts to connect to the internet, it shows the icon on the dock that is running but the edit screen doesn't appear.  Ideas for fix this?

Here is the error I'm seeing:
```
 ============================================================
 :: Asciidoc FX ::     (v1.5.6)

 Website: http://asciidocfx.com

2934 [Thread-5] ERROR com.kodedu.boot.AppStarter - Problem occured while starting AsciidocFX
javafx.fxml.LoadException:
unknown path:9

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
	at com.kodedu.boot.AppStarter.startApp(AppStarter.java:94)
	at com.kodedu.boot.AppStarter.lambda$start$0(AppStarter.java:73)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.terminalfx.FXMLController' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:353)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1090)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:929)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:971)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:220)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:744)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	... 4 common frames omitted
```

Here is my environment:
```
$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```
Mac High Sierra 10.13 with latest update on it.

Scott

**Comment by nebrass** [comment] 2017-10-22 17:26
I have the same issue. Please help 😭 

Here is my environment:
```
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

Thank you so much !

**Comment by fpzeng** [comment] 2017-10-27 15:28
The same problem。
device info:
```
MacBook Pro (Retina, 13-inch, Early 2015)
```
java info:
```
java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

**Comment by gearboxscott** [comment] 2017-10-30 20:42
I this application supported anymore?   I thinking after waiting this long and others seeing the same issue that I'm going to find another "similar" program to support my writing efforts in asciidoc.  The online asciidoc editor isn't that robust, atom support of a asciidoc preview screen doesn't support some of the options in asciidoc.   I'm looking other like textmate, slime, etc to see if they have a robust preview screen.   This is a shame because it's been great to use.

**Comment by rahmanusta** [comment] 2017-10-30 20:47
I don't have a Mac sorry. I'm starting a new job and don't have time at this moment. It is an open-source software and if you find any solution please send a pull request.

**Comment by rahmanusta** [comment] 2017-10-30 20:47
@ozlerhakan do you use  High Sierra?

**Comment by rahmanusta** [comment] 2017-10-30 20:51
Do you get any exception? Was it working in the older release of OS?

**Comment by rahmanusta** [comment] 2017-10-30 20:54
Was it working correctly in the older version?

**Comment by ozlerhakan** [comment] 2017-10-31 09:42
I'm not high enough to use it asdnsaasd, btw no @rahmanusta

**Comment by rahmanusta** [comment] 2017-10-31 10:26
Does it require a spesific hardware @ozlerhakan

**Comment by ozlerhakan** [comment] 2017-10-31 11:23
I use macOS Sierra and I am able to upgrade to high sierra without any other required hardware.

**Comment by anthonyirwin82** [comment] 2017-11-02 15:17
Is there a fix for this issue on high Sierra? I have two computers one running Sierra which works fine and the other running high Sierra and the editor does not load up just get the icon in the dock and an asciidocfx menu with nothing in it

**Comment by anthonyirwin82** [comment] 2017-11-03 06:32
Hi,

I have the jdk on my computer but not really a java developer.

I am happy to download netbeans or eclipse and run the program from source to see if I can narrow down the problem.

Anthony

On 3 November 2017 4:23:40 am AEST, Rahman Usta <notifications@github.com> wrote:
>@anthonyirwin82 Actually I don't have a mac to test it but do you get
>any exception or error when you run it. If you are a developer, you can
>run AsciidocFX with an IDE and we may see exceptions etc.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/asciidocfx/AsciidocFX/issues/329#issuecomment-341514972

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anthonyirwin82** [comment] 2017-11-03 11:55
Ok below is what I have done.

MacOS 10.13
Java 1.8.0_152 from Oracle
Maven installed with the home brew package manager: Apache Maven 3.5.2
AsciiDocFX 1.5.6 from GitHub source zip file download

~/Downloads/AsciidocFX-master $ mvn clean install
~/Downloads/AsciidocFX-master/target/appassembler/bin $ sh asciidocfx
 ============================================================
 :: Asciidoc FX ::     (v1.5.6)

 Website: http://asciidocfx.com

5507 [Thread-5] ERROR com.kodedu.boot.AppStarter - Problem occured while starting AsciidocFX 
javafx.fxml.LoadException: 
unknown path:9

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
	at com.kodedu.boot.AppStarter.startApp(AppStarter.java:94)
	at com.kodedu.boot.AppStarter.lambda$start$0(AppStarter.java:73)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.terminalfx.FXMLController' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:353)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1090)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:929)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:971)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:220)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:744)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	... 4 common frames omitted


Like I said I am not a java developer so can't really do much else then what I just did. Let me know if it's helpful or if you want me to try something else.

Regards,
Anthony

**Comment by rahmanusta** [comment] 2017-11-04 07:41
Could you please try this draft https://github.com/asciidocfx/AsciidocFX/releases/tag/untagged-c8009136cc7a558cc839

**Comment by gearboxscott** [comment] 2017-11-06 00:59
@rahmanusta, I tried to click the link of the draft above, and it comes up with a 404.  Did you open it up for collabration?

**Comment by rahmanusta** [comment] 2017-11-06 06:16
@nebrass Ahh sorry, can you access it right now?

https://github.com/asciidocfx/AsciidocFX/releases/tag/V1.5.7

**Comment by anthonyirwin82** [comment] 2017-11-06 10:17
Just ran 1.5.7 on MacOS 10.13.1 and it is loading up fine. Thanks for the fix.

**Comment by nebrass** [comment] 2017-11-06 10:42
@rahmanusta It's working 100% ! Thank you for the fix !!

**Comment by rahmanusta** [comment] 2017-11-06 11:01
Thank you guys @nebrass @anthonyirwin82 @gearboxscott . You can use this version safely, I will release this in the following days.

**Closed** 2017-11-06 14:41 UTC
