### ISSUE TITLE
MacOS - Problem rendering content

### ISSUE THREAD

**Issue by thomas-crowe** [asciidocfx/AsciidocFX#140] opened 2015-09-09 20:23 UTC
Just installed on OS X 10.10.5, upon opening an existing asciidoc I encountered an error and no document was rendered.  

From the error log
<-- Begin Paste -->
ERROR => Problem occured while rendering content
java.util.concurrent.CompletionException: netscape.javascript.JSException: SecurityError: Jail is not an absolute path: .
    at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375) ~[na:1.8.0_60]
    at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934) ~[na:1.8.0_60]
    at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:131) ~[AsciidocFX-1.3.7.jar:1.3.7]
    at com.kodcu.engine.AsciidocWebkitConverter.convertAsciidoc(AsciidocWebkitConverter.java:153) ~[AsciidocFX-1.3.7.jar:1.3.7]
    at com.kodcu.controller.ApplicationController.renderLoop(ApplicationController.java:1826) [AsciidocFX-1.3.7.jar:1.3.7]
    at com.kodcu.controller.ApplicationController.lambda$initialize$20(ApplicationController.java:548) [AsciidocFX-1.3.7.jar:1.3.7]
    at com.kodcu.service.ThreadService$1.call(ThreadService.java:35) ~[AsciidocFX-1.3.7.jar:1.3.7]
    at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: netscape.javascript.JSException: SecurityError: Jail is not an absolute path: .
    at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128) ~[jfxrt.jar:na]
    at com.sun.webkit.WebPage.twkExecuteScript(Native Method) ~[jfxrt.jar:na]
    at com.sun.webkit.WebPage.executeScript(WebPage.java:1439) ~[jfxrt.jar:na]
    at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982) ~[jfxrt.jar:na]
    at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:136) ~[AsciidocFX-1.3.7.jar:1.3.7]
    at com.kodcu.engine.AsciidocWebkitConverter.lambda$null$177(AsciidocWebkitConverter.java:123) ~[AsciidocFX-1.3.7.jar:1.3.7]
    at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295) ~[jfxrt.jar:na]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_60]
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294) ~[jfxrt.jar:na]
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]

<-- End Paste -->

I've not done much troubleshooting yet, will update as I do.

**Comment by rahmanusta** [comment] 2015-09-09 20:27
@thomas-crowe Could you share your asciidoc document or it's basic version that you are getting this exception ?

**Comment by thomas-crowe** [comment] 2015-09-09 20:40
Well, this is odd.  I went to reload the document so I could copy&paste the contents, and now it is rendering without an error.  Nothing* has changed, not even a restart of the application.  

*obviously something did to make it work, but it is not apparent to me what that change was

Apologies for the fire drill, but thank you very much for the quick response!

Thomas

**Comment by thomas-crowe** [comment] 2015-09-09 20:42
Maybe I spoke to soon...

This doc is not rendering

<-- Begin Paste -->
:noaudio:

ifdef::revealjs_slideshow[] 

[#cover,data-background-image="image/1156524-bg_redhat.png" data-background-color="#cc0000"] 
== &nbsp;

[#cover-h1] 
OpenStack 6 FASTRAX

[#cover-h2] 
Overview

[#cover-logo] 
image::{revealjs_cover_image}[] 

endif::[]




<-- End Paste -->

Error entry

<-- Begin Paste -->
ERROR => Problem occured while rendering content
java.util.concurrent.CompletionException: netscape.javascript.JSException: SecurityError: Jail is not an absolute path: .
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375) ~[na:1.8.0_60]
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934) ~[na:1.8.0_60]
	at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:131) ~[AsciidocFX-1.3.7.jar:1.3.7]
	at com.kodcu.engine.AsciidocWebkitConverter.convertAsciidoc(AsciidocWebkitConverter.java:153) ~[AsciidocFX-1.3.7.jar:1.3.7]
	at com.kodcu.controller.ApplicationController.renderLoop(ApplicationController.java:1826) [AsciidocFX-1.3.7.jar:1.3.7]
	at com.kodcu.controller.ApplicationController.lambda$initialize$20(ApplicationController.java:548) [AsciidocFX-1.3.7.jar:1.3.7]
	at com.kodcu.service.ThreadService$1.call(ThreadService.java:35) ~[AsciidocFX-1.3.7.jar:1.3.7]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: netscape.javascript.JSException: SecurityError: Jail is not an absolute path: .
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128) ~[jfxrt.jar:na]
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method) ~[jfxrt.jar:na]
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1439) ~[jfxrt.jar:na]
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982) ~[jfxrt.jar:na]
	at com.kodcu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:136) ~[AsciidocFX-1.3.7.jar:1.3.7]
	at com.kodcu.engine.AsciidocWebkitConverter.lambda$null$177(AsciidocWebkitConverter.java:123) ~[AsciidocFX-1.3.7.jar:1.3.7]
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_60]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]


<-- End Paste -->

**Comment by rahmanusta** [comment] 2015-09-09 21:04
I'm not sure for the cause but we are catching here Asciidoctor security constraints. 

I want to ask you what is the value of revealjs_cover_image

Also, can you add

:imagesdir: . // (dot)  // dont write (dot)  only .

I wonder if anything changed with imagesdir?

**Comment by thomas-crowe** [comment] 2015-09-10 20:31
Here is another document that I ran across that would not render, and reported the same error as above.

<-- Begin Paste -->
:data-uri:

== Pets vs. Farm Animals

image::images/pets_vs_farm.png[width=100%]

ifdef::showscript[]

=== Transcript

Another way to look it, metaphorically, is to compare pets to farm animals.

Pets are given names, such as *rover.internal.redhat.com*. They are unique, lovingly hand raised, and cared for. When one gets ill, you nurse it back to health.

Farm animals have tag numbers, such as *pig451.redhat.com*. They are almost identical to each other. And when one becomes ill, you get another one.


endif::showscript[]

<-- End Paste -->

I did verify that the images/pets_vs_farm.png file is present and is readable by my userid that is using asciidocFX.

I'm not sure what the value of revealjs_cover_image is (I'm brand new to asciidoc, and very much still learning, please bear with me).  I will try the change that you are suggesting to the document and report back the results.

**Comment by rahmanusta** [comment] 2015-09-13 07:50
Hi @thomas-crowe ;

For now we don't support :data-uri: feature that embeds images base64 encoded. When you remove that attribute AsciidocFX will render correctly

**Comment by rahmanusta** [comment] 2015-09-21 09:12
@thomas-crowe Do you have any question? Can we close this issue?

**Comment by thomas-crowe** [comment] 2015-09-21 11:40
Sorry, I did read your previous reply about not currently supporting the data-uri feature, and didn't think to reply.  Indeed removing the data-uri tag from the documents do enable them to render properly.  Is there any timeline for when this may be supported, I'm not a developer per se, but would be willing to help out however I can.

Thanks!

**Comment by rahmanusta** [comment] 2015-12-19 08:29
Could you please try version 1.4.5 for data-uri? https://github.com/asciidocfx/AsciidocFX/releases

**Comment by thomas-crowe** [comment] 2016-01-04 18:15
I did a quick test of just adding the :data-uri: to an existing asciidoc file I was working on, and it seemed to work.  I will try a more in-depth test later tonight.

**Comment by rahmanusta** [comment] 2016-01-04 18:17
Thank you @thomas-crowe

**Closed** 2023-07-10 05:32 UTC
