### ISSUE TITLE
Must be a memory leak somewhere

### ISSUE THREAD

**Issue by thesteve0** [asciidocfx/AsciidocFX#227] opened 2016-06-12 19:38 UTC
I LOVE AsciidocFX but it seems to have a memory leak somewhere.  I only have two documents open and AsciidocFX 1.4.5 is consuming 7.4 Gigs of memory. I am on Fedora 23 with openjdk 

 $ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Here is my AsciidocFX.vmoptions
# Enter one VM parameter per line

-Duser.language=en
-Duser.country=US
-Xmx1024M
-XX:+UseG1GC
-Djava.awt.headless=false

This also happens on my Windows machine. 

Please let me know how I can help debug this leak.

Finally, here is the process information on my machine. 

$ ps -auxw |grep java
spousty  10208 15.8 24.1 15382836 7807596 pts/1 Sl+ 12:05   4:53 /home/spousty/software/AsciidocFX/jre/bin/java -Dinstall4j.jvmDir=/home/spousty/software/AsciidocFX/jre -Dexe4j.moduleName=/home/spousty/software/AsciidocFX/AsciidocFX -Dinstall4j.launcherId=24 -Dinstall4j.swt=false -Di4jv=0 -Di4jv=0 -Di4jv=0 -Di4jv=0 -Di4jv=0 -Duser.language=en -Duser.country=US -Xmx1024M -XX:+UseG1GC -Djava.awt.headless=false -Di4j.vpt=true -classpath /home/spousty/software/AsciidocFX/.install4j/i4jruntime.jar:/home/spousty/software/AsciidocFX/lib/AsciidocFX-1.4.5.jar:/home/spousty/software/AsciidocFX/lib/avalon-framework-api-4.3.1.jar:/home/spousty/software/AsciidocFX/lib/avalon-framework-impl-4.3.1.jar:/home/spousty/software/AsciidocFX/lib/batik-anim-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-awt-util-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-bridge-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-codec-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-css-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-dom-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-ext-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-extension-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-gvt-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-parser-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-script-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-svg-dom-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-svggen-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-transcoder-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-util-1.7.jar:/home/spousty/software/AsciidocFX/lib/batik-xml-1.7.jar:/home/spousty/software/AsciidocFX/lib/classmate-1.1.0.jar:/home/spousty/software/AsciidocFX/lib/commons-io-2.4.jar:/home/spousty/software/AsciidocFX/lib/core-8.0.12.jar:/home/spousty/software/AsciidocFX/lib/de.tototec.cmdoption-0.4.1.jar:/home/spousty/software/AsciidocFX/lib/fontawesomefx-8.0.10.jar:/home/spousty/software/AsciidocFX/lib/fop-1.1.jar:/home/spousty/software/AsciidocFX/lib/hibernate-validator-5.2.2.Final.jar:/home/spousty/software/AsciidocFX/lib/install4j-1.1.jar:/home/spousty/software/AsciidocFX/lib/jackson-annotations-2.6.4.jar:/home/spousty/software/AsciidocFX/lib/jackson-core-2.6.4.jar:/home/spousty/software/AsciidocFX/lib/jackson-databind-2.6.4.jar:/home/spousty/software/AsciidocFX/lib/javax.el-3.0.0.jar:/home/spousty/software/AsciidocFX/lib/javax.json-1.0.4.jar:/home/spousty/software/AsciidocFX/lib/javax.servlet-api-3.1.0.jar:/home/spousty/software/AsciidocFX/lib/jboss-annotations-api_1.2_spec-1.0.0.Final.jar:/home/spousty/software/AsciidocFX/lib/jboss-logging-3.3.0.Final.jar:/home/spousty/software/AsciidocFX/lib/jboss-websocket-api_1.1_spec-1.1.0.Final.jar:/home/spousty/software/AsciidocFX/lib/jcl-over-slf4j-1.7.13.jar:/home/spousty/software/AsciidocFX/lib/joox-1.3.0.jar:/home/spousty/software/AsciidocFX/lib/jul-to-slf4j-1.7.13.jar:/home/spousty/software/AsciidocFX/lib/log4j-over-slf4j-1.7.13.jar:/home/spousty/software/AsciidocFX/lib/logback-classic-1.1.3.jar:/home/spousty/software/AsciidocFX/lib/logback-core-1.1.3.jar:/home/spousty/software/AsciidocFX/lib/morfologik-fsa-1.10.0.jar:/home/spousty/software/AsciidocFX/lib/morfologik-speller-1.10.0.jar:/home/spousty/software/AsciidocFX/lib/morfologik-stemming-1.10.0.jar:/home/spousty/software/AsciidocFX/lib/odfdom-java-0.8.8-incubating.jar:/home/spousty/software/AsciidocFX/lib/plantuml-8033.jar:/home/spousty/software/AsciidocFX/lib/saxon-6.5.3.jar:/home/spousty/software/AsciidocFX/lib/simple-odf-0.7-incubating.jar:/home/spousty/software/AsciidocFX/lib/slf4j-api-1.7.13.jar:/home/spousty/software/AsciidocFX/lib/spring-aop-4.2.4.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-beans-4.2.4.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-boot-1.3.1.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-boot-autoconfigure-1.3.1.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-boot-starter-1.3.1.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-boot-starter-logging-1.3.1.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-boot-starter-undertow-1.3.1.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-boot-starter-validation-1.3.1.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-boot-starter-web-1.3.1.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-boot-starter-websocket-1.3.1.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-context-4.2.4.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-core-4.2.4.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-expression-4.2.4.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-web-4.2.4.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-webmvc-4.2.4.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/spring-websocket-4.2.4.RELEASE.jar:/home/spousty/software/AsciidocFX/lib/taglets-0.8.8-incubating.jar:/home/spousty/software/AsciidocFX/lib/tomcat-embed-el-8.0.30.jar:/home/spousty/software/AsciidocFX/lib/undertow-core-1.3.10.Final.jar:/home/spousty/software/AsciidocFX/lib/undertow-servlet-1.3.10.Final.jar:/home/spousty/software/AsciidocFX/lib/undertow-websockets-jsr-1.3.10.Final.jar:/home/spousty/software/AsciidocFX/lib/validation-api-1.1.0.Final.jar:/home/spousty/software/AsciidocFX/lib/xalan-2.6.0.jar:/home/spousty/software/AsciidocFX/lib/xercesImpl-2.9.1.jar:/home/spousty/software/AsciidocFX/lib/xml-apis-1.3.04.jar:/home/spousty/software/AsciidocFX/lib/xml-apis-ext-1.3.04.jar:/home/spousty/software/AsciidocFX/lib/xmlgraphics-commons-1.5.jar:/home/spousty/software/AsciidocFX/lib/xnio-api-3.3.3.Final.jar:/home/spousty/software/AsciidocFX/lib/xnio-nio-3.3.3.Final.jar:/home/spousty/software/AsciidocFX/lib/xslthl-2.1.0.jar:/home/spousty/software/AsciidocFX/lib/zt-exec-1.8.jar com.install4j.runtime.launcher.UnixLauncher launch b29879e0 /home/spousty/software/AsciidocFX/log/asciidocfx.log+  com.kodcu.boot.AppStarter

**Comment by rahmanusta** [comment] 2016-06-12 19:49
Hello @thesteve0 ,

It is very interesting to consume 7.4 Gig, I didn't see or get feedback about it. if your used documents are open, I can try the AsciidocFX with them.

You can profile the application when running with any profiler like yourkit, jprofiler eg. They helps to much to see what eats how much memory.

**Comment by thesteve0** [comment] 2016-06-14 02:53
Hey Rahman 
Thanks so much for the quick response. Please go to this repo and branch:
https://github.com/thesteve0/discoverycenter/tree/adding-db

Then open this file:
https://github.com/thesteve0/discoverycenter/blob/adding-db/source/samples/styleguide.html.adoc

and then start editing this file:

https://github.com/thesteve0/discoverycenter/blob/adding-db/source/developer/databases/connecting-to-db.html.adoc

As you edit more and more the memory footprint keeps growing. I have never set up a profiler before so if you know of a free one and some easy instructions I can do that as well.

**Comment by rahmanusta** [comment] 2016-06-14 14:06
Hi @thesteve0 ,

I tried this way but couldn't face with such that issue. My JDK version is 1.8.0_92

You tried it in two OS, but are their hardware is same (especially CPU)?

Can you try again after disable the spell-checker? To disable right click > SpellChecker > Disable

**Comment by thesteve0** [comment] 2016-07-06 22:48
This is with spelling turned off. I am using the bundled JRE with asciidocfx. It starts off fine and then just keeps consuming memory as I edit documents. 

Again I would appreciate instructions on how to help you debug and get to the bottom of this. 

![screenshot from 2016-07-06 15-46-08](https://cloud.githubusercontent.com/assets/1404099/16637027/d541f532-4390-11e6-8acd-84c7a1d7fb51.png)

**Comment by thesteve0** [comment] 2016-07-14 17:04
Bump

**Comment by rahmanusta** [comment] 2016-07-14 17:35
Hi @thesteve0 , we should make a teamviewer session to see what eats the memory.

**Comment by sillyfly** [comment] 2016-07-21 07:08
Can you try running with `-Dprism.order=sw` (to force software-rendering)?  

Also - which GPU and kernel version are you using? I'm getting similar results (in other JavaFX applications) with Intel GPU and kernel 4.6.

**Comment by rahmanusta** [comment] 2016-07-21 07:12
@thesteve0 Edit AsciidocFX.vmoptions file to add above parameter. The file is located at AsciidocFX installation directory.

**Comment by lmrv** [comment] 2016-08-11 12:00
Hello.

Same problem here, on Linux 4.6 (Arch) with AsciidocFX 1.4.6 and 1.4.7 with or witout jre embedded.
Forcing software-rendering works for me.

**Comment by rahmanusta** [comment] 2016-09-25 16:44
Do you report that this issue is still exist with version 1.5.0 ?

**Comment by sillyfly** [comment] 2016-10-09 14:03
Rahman - I have not tried AsciidocFX, but AFAIK the underlying source in the JRE was not fixed in any recent JRE updates.    

As for reproducibility - It seems the only factor is having Mesa >= 11.0 (Both 11 and 12 versions exhibit similar problems on my system, and all confirmed cases where the problem does not occur were using Mesa 10 or not using Mesa at all [NVidia GLX, for example]).  

Unless you have removed all usages of JavaFX animations and animation timers (including process indicator etc.) I doubt there will be any change. 
I will try to install AsciidocFX on my system later to confirm this, but I'm afraid the only real solution would be to identify the bug in Mesa, or confirm JavaFX's usage of Mesa is erroneous (latest openjfx-dev discussion concluded they weren't doing anything wrong, and if there's a bug it's in Mesa).

**Comment by sillyfly** [comment] 2016-10-10 07:51
It seems AsciidocFX completely fails to start on my system, so I can't test this. The error I'm getting is:  

    #
    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  SIGSEGV (0xb) at pc=0x00007f3fb3335c58, pid=18133, tid=0x00007f3fcaf7b700
    #
    # JRE version: OpenJDK Runtime Environment (8.0_102-b14) (build 1.8.0_102-8u102-b14.1-2-b14)
    # Java VM: OpenJDK 64-Bit Server VM (25.102-b14 mixed mode linux-amd64 compressed oops)
    # Problematic frame:
    # C  [libjfxwebkit.so+0x1883c58]
    #

I'm guessing this is unrelated, though.

**Comment by sillyfly** [comment] 2016-10-10 08:28
Got the bundled JRE version to work (not sure why it didn't like my system JRE), and after about 10 minutes playing around the memory usage was >5GB. As the JVM max memory is set to 1GB I'd say this memory leak is still present.

**Comment by rahmanusta** [comment] 2016-10-10 08:36
@sillyfly What if we remove JavaFX animations ? I assume we only use animations in ProgressBar component ?

**Comment by sillyfly** [comment] 2016-11-29 12:18
Recent updates of Mesa + X.org have solved such issues on my system, so it's possible this will no longer be an issue.  

Make sure you have Mesa >=13.0.1 and X.org>=1.18.4 - with these versions I'm no longer experiencing memory leaks on JavaFX animations.

**Comment by rahmanusta** [comment] 2016-11-29 12:29
That is a good news @sillyfly, Thanks.

**Closed** 2023-07-10 05:37 UTC
